### ISSUE TITLE
"too many redirects" error on /wp-admin/

### ISSUE THREAD

**Issue by michaelpporter** [wodby/docker4wordpress#22]
Only on my local docker instance:

When I logged in I get a "too many redirects" error on `/wp-admin/` I am able to get to `/wp-admin/index.php` or another page in the admin. I do not have this issue on our staging server or on the production site. 

This prevents local behat tests that login as they get caught in the redirect.

I tried nginx, the wp-admin works but magento stops working.

### Codebase
Built-in vanilla WordPress with Margento in /shop
  
### Host OS 
macOS High Sierra

### Docker info output
```
Containers: 35
 Running: 7
 Paused: 0
 Stopped: 28
Images: 34
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.834GiB
Name: moby
ID: HIJS:6MNP:4ICG:D46E:U25X:Z3SO:NOPL:YW5E:2SEZ:VAZR:JHAU:XKIW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 91
 Goroutines: 115
 System Time: 2017-09-13T14:17:56.4285866Z
 EventsListeners: 3
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```yml
# Content of your docker-compose.yml file. Make sure you remove all sensible information you version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  php:
    image: wodby/wordpress-php:7.0-2.2.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_OUTPUT_BUFFERING: 'On'
      PHP_OUTPUT_HANDLER: mb_output_handler
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - semitrailers-sync:/var/www/html # Docker-sync

  apache:
    image: wodby/wordpress-apache:2.4-1.0.0
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/www
      HOME: /var/www/html/www
    volumes:
      - semitrailers-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=semitrailers_apache_1'
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:semitrailers.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=semitrailers_mailhog_1'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.semitrailers.docker.localhost'

volumes:
  semitrailers-sync:
    external: true
```
```yml
# Content of your docker-sync.yml file. Make sure you remove all sensible information you 
version: "2"

options:
  verbose: true
syncs:
  semitrailers-sync: # tip: add -sync and you keep consistent names as a convention
    src: '.'
    sync_userid: '82'
    # sync_strategy: 'native_osx' # not needed, this is the default now
    sync_excludes: ['.gitignore', '.git/', '.idea/']

```

```yml
# Content of your traefik.yml file. Make sure you remove all sensible information you 
version: '2'
services:
    traefik:
        image: traefik
        restart: unless-stopped
        command: '-c /dev/null --web --docker --logLevel=INFO'
        networks:
            - sites
            - semitrailers
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
            - '9000:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './traefik/test:/certs'
    portainer:
        image: portainer/portainer
        command: '--no-auth'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        labels:
            - traefik.backend=portainer
            - traefik.port=9000
            - 'traefik.frontend.rule=Host:portainer.docker.localhost'
networks:
    sites:
        external:
            name: sites_default
    semitrailers:
        external:
            name: semitrailers_default

```

```
# Run "docker-compose logs [service]". Let's say you get 500 error for some reason then it'll be php_1      | 172.21.0.6 -  13/Sep/2017:14:21:30 +0000 "GET /index.php" 302
apache_1   | [Wed Sep 13 14:21:30.480012 2017] [proxy:debug] [pid 22:tid 140393650887400] proxy_util.c(2171): AH00943: FCGI: has released connection for (php)
apache_1   | 172.21.0.2 - - [13/Sep/2017:14:21:30 +0000] "GET /wp-admin/ HTTP/1.1" 302 -
apache_1   | [Wed Sep 13 14:21:30.486947 2017] [authz_core:debug] [pid 22:tid 140393652779752] mod_authz_core.c(809): [client 172.21.0.2:35734] AH01626: authorization result of Require all granted: granted
apache_1   | [Wed Sep 13 14:21:30.486975 2017] [authz_core:debug] [pid 22:tid 140393652779752] mod_authz_core.c(809): [client 172.21.0.2:35734] AH01626: authorization result of <RequireAny>: granted
apache_1   | [Wed Sep 13 14:21:30.487101 2017] [authz_core:debug] [pid 22:tid 140393652779752] mod_authz_core.c(809): [client 172.21.0.2:35734] AH01626: authorization result of Require all granted: granted
apache_1   | [Wed Sep 13 14:21:30.487368 2017] [authz_core:debug] [pid 22:tid 140393652779752] mod_authz_core.c(809): [client 172.21.0.2:35734] AH01626: authorization result of <RequireAny>: granted
apache_1   | [Wed Sep 13 14:21:30.487606 2017] [proxy:debug] [pid 22:tid 140393652779752] mod_proxy.c(1228): [client 172.21.0.2:35734] AH01143: Running scheme fcgi handler (attempt 0)
apache_1   | [Wed Sep 13 14:21:30.487628 2017] [proxy_fcgi:debug] [pid 22:tid 140393652779752] mod_proxy_fcgi.c(913): [client 172.21.0.2:35734] AH01076: url: fcgi://php:9000/var/www/html/www/index.php proxyname: (null) proxyport: 0
apache_1   | [Wed Sep 13 14:21:30.487636 2017] [proxy_fcgi:debug] [pid 22:tid 140393652779752] mod_proxy_fcgi.c(920): [client 172.21.0.2:35734] AH01078: serving URL fcgi://php:9000/var/www/html/www/index.php
apache_1   | [Wed Sep 13 14:21:30.487655 2017] [proxy:debug] [pid 22:tid 140393652779752] proxy_util.c(2156): AH00942: FCGI: has acquired connection for (php)
apache_1   | [Wed Sep 13 14:21:30.487663 2017] [proxy:debug] [pid 22:tid 140393652779752] proxy_util.c(2209): [client 172.21.0.2:35734] AH00944: connecting fcgi://php:9000/var/www/html/www/index.php to php:9000
apache_1   | [Wed Sep 13 14:21:30.487689 2017] [proxy:debug] [pid 22:tid 140393652779752] proxy_util.c(2418): [client 172.21.0.2:35734] AH00947: connected /var/www/html/www/index.php to php:9000
apache_1   | [Wed Sep 13 14:21:30.488466 2017] [proxy:debug] [pid 22:tid 140393652779752] proxy_util.c(2884): AH02824: FCGI: connection established with 172.21.0.3:9000 (php)
php_1      | 172.21.0.6 -  13/Sep/2017:14:21:30 +0000 "GET /index.php" 302
```
