### ISSUE TITLE
Can't enable PHP 7.2

### ISSUE THREAD

**Issue by ecotechie** [wodby/docker4wordpress#44]
Trying to set Docker to load PHP 7.2. 
.env file has these set:
WORDPRESS_TAG=5-4.12.0
PHP_TAG=7.2-dev-4.12.0

But still loading PHP 7.3.2. Hoping to have 7.2 load in order to use XDebug in local development.

I've ran make prune but PHP never seems to change.

### Codebase
Vanilla WordPress
  
### Host OS 
Linux - Ubuntu 18.04.1 LTS

### Docker info output
```
Containers: 33
 Running: 7
 Paused: 0
 Stopped: 26
Images: 20
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.27GiB
Name: Thor
ID: WWOS:KNGT:SH4E:B6GO:UQME:QVDZ:KENI:T7FI:VCTE:5UVX:FCCQ:WZDA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

```

### Docker compose file
```yml
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./database:/var/lib/mysql

  php:
    image: wodby/wordpress-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_SESSION: xdebug-atom
      PHP_XDEBUG_REMOTE_HOST: 10.0.0.20
      PHP_XDEBUG_REMOTE_LOG: /var/www/html/xdebug.log
    volumes:
      - ./html:/var/www/html
      - files:/mnt/files

  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
    volumes:
      - ./html:/var/www/html
    labels:
      - 'traefik.backend=${PROJECT_NAME}_apache'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  webgrind:
    image: wodby/webgrind:$WEBGRIND_TAG
    container_name: "${PROJECT_NAME}_webgrind"
    environment:
      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
    labels:
      - 'traefik.backend=${PROJECT_NAME}_webgrind'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:webgrind.${PROJECT_BASE_URL}'
    volumes:
      - files:/mnt/files

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=${PROJECT_NAME}_pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=${PROJECT_NAME}_portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  files:

```

### Docker compose override file
```yml
version: "3"

services:
  php:
    image: wodby/wordpress:$WORDPRESS_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./html:/var/www/html

  apache:
    volumes:
      - ./html:/var/www/html

volumes:
  codebase:
```
