### ISSUE TITLE
Redis won't connect with WP plugin

### ISSUE THREAD

**Issue by otravers** [Wodby/docker4wordpress#6]
When I added define('WP_REDIS_HOST', 'redis'); to my wp-config.php file, the Redis Object Cache settings page would stay "Status: Not Connected" after clicking the "Enable Object Cache" button.

Once I changed wp-config to define('WP_REDIS_HOST', '127.0.0.1'), the Redis Object Cache plugin setting page did show Status: Connected. I disconnected just to test again with "redis", wouldn't work, I put 127.0.0.1 again which now doesn't work anymore!

Kitematic shows the Redis container log with "the server is now ready to accept connections on port 6379." If I run "docker exec -it mywordpress_redis_1 redis-cli" from the command line, I do get a prompt  showing "127.0.0.1:6379"

In the WP plugin the Servers table shows 1 entry:
Alias	Protocol	Host	Port	Database	Password
Master	TCP	127.0.0.1	6379 	0	No

I then set a password under environment: in the docker-compose redis: service, followed by docker-compose up -d. I then added that same password to wp-config, now the plugin settings show:
Alias	Protocol	Host	Port	Database	Password
Master	TCP	127.0.0.1	6379 	0	Yes

But I still can't connect. I also set WP_REDIS_PORT and WP_REDIS_DATABASE for good measure, no dice.

This is with Redis 3.2.3 and, Redis Object Cache 1.3.4 under WP 4.6.1, with a slightly modified version of your package (I run WP as a container from the wordpress-fpm image) under the latest Docker for Windows.

**Comment by PavelPrischepa** [comment]
Hi @otravers,

> define('WP_REDIS_HOST', 'redis');

It's a correct value of the Redis hostname, so it should work.

What's in the redis log `docker-compose logs redis`?

Also, try to connect to the redis from the php.
```
# docker-compose exec php sh

# ping redis
PING redis (172.20.0.7): 56 data bytes
64 bytes from 172.20.0.7: seq=0 ttl=64 time=0.178 ms
64 bytes from 172.20.0.7: seq=1 ttl=64 time=0.120 ms

# telnet redis 6379
set testkey 10
get testkey
```

**Comment by otravers** [comment]
I deleted my Redis container, switched back to define('WP_REDIS_HOST', 'redis');, started again the Redis container, can now properly connect. Not sure what happened, sorry for the trouble and you can close this ticket.

Thanks also for your troubleshooting tips, I also installed this web interface to better see what's going on with Redis:
https://github.com/o/redis-info

**Comment by robertzas** [comment]
I have this same issue, but I cannot connect at either 
```php
define('WP_REDIS_HOST', 'redis');
```
nor
```php
define('WP_REDIS_HOST', '127.0.0.1');
```
here is the docker-compose.yml I am using:

```yaml
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./mysql:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/wordpress:4-7.1-2.1.0
    # image: wodby/wordpress-php:7.1-2.1.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./wordpress:/var/www/html
#      - d4d-unison-sync:/var/www/html # Docker-sync for macOS users

  nginx:
    image: wodby/wordpress-nginx:4-1.10-2.1.0
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/
    volumes:
      - ./wordpress:/var/www/html
#      - d4d-unison-sync:/var/www/html # Docker-sync for macOS users
    depends_on:
      - php
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:wp.docker.localhost'

  varnish:
    image: wodby/wordpress-varnish:4.1-2.1.0
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
    labels:
      - 'traefik.backend=varnish'
      - 'traefik.port=6081'
      - 'traefik.frontend.rule=Host:varnish.wp.docker.localhost'

  redis:
    image: wodby/redis:3.2-2.1.0
    volumes:
    #  - ./redis:/

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.wp.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.wp.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
