### ISSUE TITLE
Problem with connect to api endpoint.

### ISSUE THREAD

**Issue by grzesiek1owline** [wodby/docker4wordpress#73]
Hi, I created endpoint Api in my Wordpress, but i cant connect with Enpoint URL.
Project URL : talenti.owline
Endpoint URL: talenti.owline/wp-json/form/acf

I try to coonnect with curl() and file_get_contents(), but always i have a error

```
Error#7: Failed to connect to talenti.owline port 80: Connection refused
```

### Codebase
Built-in vanilla WordPress with Sage Roots Theme
  
### Host OS 
Ubuntu 20.04

### Docker info output
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 27
  Running: 8
  Paused: 0
  Stopped: 19
 Images: 38
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-55-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.23GiB
 Name: owline-Lenovo-Legion-5-15ARH05
 ID: GRKT:CPZT:P2NZ:KMMP:6EHO:ZOUM:ULZ4:RMLD:5KAA:VXIR:AQ7Q:BA4F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### Project Docker compose file
Make sure you remove all commented services.
```yml
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
#    - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    - ./db:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/wordpress-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
#      # Read instructions at https://wodby.com/docs/stacks/wordpress/local#xdebug
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=phpStorm
      PHP_XDEBUG_IDEKEY: "phpStorm"
      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows
      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
    volumes:
    - ./web:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/wordpress/local#docker-for-mac
#    - mutagen:/var/www/html
#    # For XHProf and Xdebug profiler traces
#    - files:/mnt/files

  crond:
    image: wodby/wordpress-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * wp cron event run --due-now --path=/var/www/html"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
    - ./web:/var/www/html:cached

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: wordpress
      #NGINX_SERVER_ROOT: /var/www/html/subdir
    volumes:
    - ./web:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/wordpress/local#docker-for-mac
#    - mutagen:/var/www/html
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
    - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  adminer:
    container_name: "${PROJECT_NAME}_adminer"
    image: wodby/adminer:$ADMINER_TAG
    environment:
##      # For PostgreSQL:
##      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`adminer.${PROJECT_BASE_URL}`)"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"
```

### Traefik Docker compose file
```yml
version: '3'

services:
  traefik:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    networks:
    - threnton
    - sportsmed
    - talenti
    - joggas
    - sustain
    ports:
    - '80:80'
    - '8080:8080'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  threnton:
    external:
      name: threnton_default
  sportsmed:
    external:
      name: sportsmed_default
  talenti:
    external:
      name: talenti_default
  joggas:
    external:
      name: joggas_default
  sustain:
    external:
      name: sustainabilityguide_default

```

### Logs output
```
2021/06/22 08:03:19 [notice] 48#48: *39 "/wp-admin$" does not match "/kariera/formularz-uzytkownika/", client: 172.27.0.2, server: default, request: "GET /kariera/formularz-uzytkownika/ HTTP/1.1", host: "talenti.owline"
2021/06/22 08:03:19 [notice] 48#48: *39 "^/[_0-9a-zA-Z-]+(/wp-.*)" does not match "/kariera/formularz-uzytkownika/", client: 172.27.0.2, server: default, request: "GET /kariera/formularz-uzytkownika/ HTTP/1.1", host: "talenti.owline"
2021/06/22 08:03:19 [notice] 48#48: *39 "^/[_0-9a-zA-Z-]+(/.*\.php)$" does not match "/kariera/formularz-uzytkownika/", client: 172.27.0.2, server: default, request: "GET /kariera/formularz-uzytkownika/ HTTP/1.1", host: "talenti.owline"
2021/06/22 08:03:19 [notice] 48#48: *39 "/wp-admin$" does not match "/kariera/formularz-uzytkownika/", client: 172.27.0.2, server: default, request: "GET /kariera/formularz-uzytkownika/ HTTP/1.1", host: "talenti.owline"
2021/06/22 08:03:19 [notice] 48#48: *39 "/wp-admin$" does not match "/index.php", client: 172.27.0.2, server: default, request: "GET /kariera/formularz-uzytkownika/ HTTP/1.1", host: "talenti.owline"
2021/06/22 08:03:20 [notice] 48#48: *42 "/wp-admin$" does not match "/wp-admin/admin-ajax.php", client: 172.27.0.2, server: default, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", host: "talenti.owline", referrer: "http://talenti.owline/wp-admin/"
172.27.0.2 - - [22/Jun/2021:08:03:22 +0000] "GET /kariera/formularz-uzytkownika/ HTTP/1.1" 200 23813 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
172.27.0.2 - - [22/Jun/2021:08:03:22 +0000] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 78 "http://talenti.owline/wp-admin/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
```
