### ISSUE TITLE
How to forward the connection from AWS EC2 to Localhost?

### ISSUE THREAD

**Issue by rambalachandran** [wodby/docker4wordpress#79]
### Codebase
Built-in vanilla WordPress release 5.4.45
  
### Host OS 
Ubuntu 20.04 on AWS EC2

### Docker info output
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-1022-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 968.9MiB
 Name: ip-172-31-46-131
 ID: VDJV:JPC2:ELJ3:PG32:YZZ4:5UIZ:LOTK:YGHC:BYFG:VRXW:L4FF:2DV7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker compose file
Make sure you remove all commented services.
```yml
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
#    volumes:
#    - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#    - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/wordpress-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
#      # Read instructions at https://wodby.com/docs/stacks/wordpress/local#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_MODE: debug
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows
#      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
    volumes:
    - ./:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/wordpress/local#docker-for-mac
#    - wordpress:/var/www/html
#    # For XHProf and Xdebug profiler traces
#    - files:/mnt/files

  crond:
    image: wodby/wordpress-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * wp cron event run --due-now --path=/var/www/html"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
    - ./:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/wordpress/local#docker-for-mac
#    - wordpress:/var/www/html

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: wordpress
      #NGINX_SERVER_ROOT: /var/www/html/subdir
    volumes:
    - ./:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/wordpress/local#docker-for-mac
#    - wordpress:/var/www/html
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
    - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

#  apache:
#    image: wodby/apache:$APACHE_TAG
#    container_name: "${PROJECT_NAME}_apache"
#    depends_on:
#    - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_VHOST_PRESET: php
#    volumes:
#    - ./:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/wordpress/local#docker-for-mac
#    - wordpress:/var/www/html
#    labels:
#    - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"

#  varnish:
#    image: wodby/varnish:$VARNISH_TAG
#    container_name: "${PROJECT_NAME}_varnish"
#    depends_on:
#    - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#      VARNISH_CONFIG_PRESET: wordpress
#      VARNISH_ALLOW_UNRESTRICTED_PURGE: 1
#    labels:
#    - "traefik.http.services.${PROJECT_NAME}_varnish.loadbalancer.server.port=6081"
#    - "traefik.http.routers.${PROJECT_NAME}_varnish.rule=Host(`varnish.${PROJECT_BASE_URL}`)"

#  redis:
#    container_name: "${PROJECT_NAME}_redis"
#    image: wodby/redis:$REDIS_TAG

#  adminer:
#    container_name: "${PROJECT_NAME}_adminer"
#    image: wodby/adminer:$ADMINER_TAG
#    environment:
#      ADMINER_DEFAULT_DB_HOST: $DB_HOST
#      ADMINER_DEFAULT_DB_NAME: $DB_NAME
#    labels:
#    - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`adminer.${PROJECT_BASE_URL}`)"

#  webgrind:
#    image: wodby/webgrind:$WEBGRIND_TAG
#    container_name: "${PROJECT_NAME}_webgrind"
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug
#    labels:
#    - "traefik.http.routers.${PROJECT_NAME}_webgrind.rule=Host(`webgrind.${PROJECT_BASE_URL}`)"
#    volumes:
#    - files:/mnt/files

#  pma:
#    image: phpmyadmin/phpmyadmin
#    container_name: "${PROJECT_NAME}_pma"
#    environment:
#      PMA_HOST: $DB_HOST
#      PMA_USER: $DB_USER
#      PMA_PASSWORD: $DB_PASSWORD
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#    - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:$ATHENAPDF_TAG
#    container_name: "${PROJECT_NAME}_athenapdf"
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: "false"

#  blackfire:
#    image: blackfire/blackfire
#    container_name: "${PROJECT_NAME}_blackfire"
#    environment:
#      BLACKFIRE_SERVER_ID: XXXXX
#      BLACKFIRE_SERVER_TOKEN: YYYYY

#  solr:
#    image: wodby/solr:$SOLR_TAG
#    container_name: "${PROJECT_NAME}_solr"
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#    - "traefik.http.services.${PROJECT_NAME}_solr.loadbalancer.server.port=8983"
#    - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"

#  elasticsearch:
#    image: wodby/elasticsearch:$ELASTICSEARCH_TAG
#    environment:
#      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

#  kibana:
#    image: wodby/kibana:$KIBANA_TAG
#    depends_on:
#    - elasticsearch
#    labels:
#    - "traefik.http.services.${PROJECT_NAME}_kibana.loadbalancer.server.port=5601"
#    - "traefik.http.routers.${PROJECT_NAME}_kibana.rule=Host(`kibana.${PROJECT_BASE_URL}`)"

#  node:
#    image: wodby/node:$NODE_TAG
#    container_name: "${PROJECT_NAME}_node"
#    working_dir: /app
#    labels:
#    - "traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000"
#    - "traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`node.${PROJECT_BASE_URL}`)"
#    expose:
#    - "3000"
#    volumes:
#    - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    container_name: "${PROJECT_NAME}_memcached"
#    image: wodby/memcached:$MEMCACHED_TAG

#  opensmtpd:
#    container_name: "${PROJECT_NAME}_opensmtpd"
#    image: wodby/opensmtpd:$OPENSMTPD_TAG

#  rsyslog:
#    container_name: "${PROJECT_NAME}_rsyslog"
#    image: wodby/rsyslog:$RSYSLOG_TAG

#  xhprof:
#    image: wodby/xhprof:$XHPROF_TAG
#    restart: always
#    volumes:
#    - files:/mnt/files
#    labels:
#    - "traefik.http.routers.${PROJECT_NAME}_xhprof.rule=Host(`xhprof.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - '8000:80'
#    - '8080:8080' # Dashboard
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

#x-mutagen:
#  sync:
#    defaults:
#      ignore:
#        vcs: true
#        paths:
#        - .DS_Store
#        - .history
#        - .idea
#    wordpress:
#      alpha: "."
#      beta: "volume://wordpress"
#      configurationBeta:
#        permissions:
#          defaultFileMode: 0644
#          defaultDirectoryMode: 0755
#          defaultOwner: "id:501"
#          defaultGroup: "id:20"

#volumes:
## For macOS users (Mutagen)
#  wordpress:
## For Xdebug profiler
#  files:
```

### Logs output
```
Attaching to my_wordpress_project_nginx, my_wordpress_project_traefik, my_wordpress_project_crond, my_wordpress_project_mariadb, my_wordpress_project_php, my_wordpress_project_mailhog
my_wordpress_project_crond | sudo -E init
my_wordpress_project_crond | [25-Mar-2022 10:31:53 UTC] PHP Deprecated:  file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php on line 886
my_wordpress_project_crond | [25-Mar-2022 10:31:54 UTC] PHP Deprecated:  file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php on line 886
my_wordpress_project_crond | /usr/local/bin/compare_semver: line 28: ((: 10#Deprecated: value too great for base (error token is "10#Deprecated")
my_wordpress_project_crond | /usr/local/bin/compare_semver: line 32: ((: 10#Deprecated: value too great for base (error token is "10#Deprecated")
my_wordpress_project_crond | crond: crond (busybox 1.32.1) started, log level 0
my_wordpress_project_crond | crond: user:www-data entry:0 * * * * wp cron event run --due-now --path=/var/www/html
my_wordpress_project_crond | 100000000000000000000000000000000000000000000000000000000000
my_wordpress_project_crond | 111111111111111111111111
my_wordpress_project_crond | 11111111111111111111111111111111
my_wordpress_project_crond | 111111111111
my_wordpress_project_crond | 1111111
my_wordpress_project_crond | crond: user:www-data entry:0 * * * * wp cron event run --due-now --path=/var/www/html
my_wordpress_project_crond | 100000000000000000000000000000000000000000000000000000000000
my_wordpress_project_crond | 111111111111111111111111
my_wordpress_project_crond | 11111111111111111111111111111111
my_wordpress_project_crond | 111111111111
my_wordpress_project_crond | 1111111
my_wordpress_project_crond | crond: wakeup dt=6
my_wordpress_project_crond | crond: file www-data:
my_wordpress_project_crond | crond:  line wp cron event run --due-now --path=/var/www/html
my_wordpress_project_crond | crond: wakeup dt=60
my_wordpress_project_crond | crond: file www-data:
my_wordpress_project_crond | crond:  line wp cron event run --due-now --path=/var/www/html
my_wordpress_project_crond | crond: wakeup dt=60
my_wordpress_project_crond | crond: file www-data:
my_wordpress_project_crond | crond:  line wp cron event run --due-now --path=/var/www/html
my_wordpress_project_crond | crond: wakeup dt=60
my_wordpress_project_crond | crond: file www-data:
my_wordpress_project_crond | crond:  line wp cron event run --due-now --path=/var/www/html
my_wordpress_project_mailhog | 2022/03/25 10:31:51 Using in-memory storage
my_wordpress_project_mailhog | 2022/03/25 10:31:51 [SMTP] Binding to address: 0.0.0.0:1025
my_wordpress_project_mailhog | 2022/03/25 10:31:51 Serving under http://0.0.0.0:8025/
my_wordpress_project_mailhog | [HTTP] Binding to address: 0.0.0.0:8025
my_wordpress_project_mailhog | Creating API v1 with WebPath: 
my_wordpress_project_mailhog | Creating API v2 with WebPath: 
my_wordpress_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_wordpress_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_wordpress_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_wordpress_project_mariadb | 2022-03-25T10:31:52+0000 [Note] [Entrypoint]: Entrypoint script for MySQL Server  started.
my_wordpress_project_mariadb | 2022-03-25T10:31:53+0000 [Note] [Entrypoint]: Initializing database files
my_wordpress_project_mariadb | 2022-03-25 10:31:53 0 [Warning] 'innodb-buffer-pool-instances' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:53 0 [Warning] 'innodb-force-load-corrupted' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:53 0 [Warning] 'innodb-log-files-in-group' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
my_wordpress_project_mariadb | To do so, start the server, then issue the following command:
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | '/usr/bin/mysql_secure_installation'
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | which will also give you the option of removing the test
my_wordpress_project_mariadb | databases and anonymous user created by default.  This is
my_wordpress_project_mariadb | strongly recommended for production servers.
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | See the MariaDB Knowledgebase at https://mariadb.com/kb
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | Please report any problems at https://mariadb.org/jira
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | The latest information about MariaDB is available at https://mariadb.org/.
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | Consider joining MariaDB's strong and vibrant community:
my_wordpress_project_mariadb | https://mariadb.org/get-involved/
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | 2022-03-25T10:31:55+0000 [Note] [Entrypoint]: Database files initialized
my_wordpress_project_mariadb | 2022-03-25T10:31:55+0000 [Note] [Entrypoint]: Starting temporary server
my_wordpress_project_mariadb | 2022-03-25T10:31:55+0000 [Note] [Entrypoint]: Waiting for server startup
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] mysqld (server 10.7.3-MariaDB) starting as process 91 ...
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Number of transaction pools: 1
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Using Linux native AIO
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Completed initialization of buffer pool
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: 128 rollback segments are active.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Creating shared tablespace for temporary tables
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: 10.7.3 started; log sequence number 42179; transaction id 14
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] Plugin 'FEEDBACK' is disabled.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Warning] 'innodb-buffer-pool-instances' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Warning] 'innodb-force-load-corrupted' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Warning] 'innodb-log-files-in-group' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] InnoDB: Buffer pool(s) load completed at 220325 10:31:55
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Warning] 'user' entry 'root@6d081ad42455' ignored in --skip-name-resolve mode.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Warning] 'proxies_priv' entry '@% root@6d081ad42455' ignored in --skip-name-resolve mode.
my_wordpress_project_mariadb | 2022-03-25 10:31:55 0 [Note] mysqld: ready for connections.
my_wordpress_project_mariadb | Version: '10.7.3-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
my_wordpress_project_mariadb | 2022-03-25T10:31:56+0000 [Note] [Entrypoint]: Temporary server started.
my_wordpress_project_mariadb | 2022-03-25 10:31:58 5 [Warning] 'proxies_priv' entry '@% root@6d081ad42455' ignored in --skip-name-resolve mode.
my_wordpress_project_mariadb | 2022-03-25T10:31:58+0000 [Note] [Entrypoint]: Creating database wordpress
my_wordpress_project_mariadb | 2022-03-25T10:31:58+0000 [Note] [Entrypoint]: Creating user wordpress
my_wordpress_project_mariadb | 2022-03-25T10:31:58+0000 [Note] [Entrypoint]: Giving user wordpress access to schema wordpress
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | 2022-03-25T10:31:58+0000 [Note] [Entrypoint]: Stopping temporary server
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] InnoDB: FTS optimize thread exiting.
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] InnoDB: Starting shutdown...
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] InnoDB: Buffer pool(s) dump completed at 220325 10:31:58
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] InnoDB: Shutdown completed; log sequence number 42191; transaction id 15
my_wordpress_project_mariadb | 2022-03-25 10:31:58 0 [Note] mysqld: Shutdown complete
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | 2022-03-25T10:31:59+0000 [Note] [Entrypoint]: Temporary server stopped
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | 2022-03-25T10:31:59+0000 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
my_wordpress_project_mariadb | 
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] mysqld (server 10.7.3-MariaDB) starting as process 1 ...
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Number of transaction pools: 1
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Using Linux native AIO
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Completed initialization of buffer pool
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: 128 rollback segments are active.
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Creating shared tablespace for temporary tables
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: 10.7.3 started; log sequence number 42191; transaction id 14
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] Plugin 'FEEDBACK' is disabled.
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Warning] 'innodb-buffer-pool-instances' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Warning] 'innodb-force-load-corrupted' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Warning] 'innodb-log-files-in-group' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] Server socket created on IP: '0.0.0.0'.
my_wordpress_project_nginx | 2022/03/25 10:31:53 [notice] 1#1: using the "epoll" event method
my_wordpress_project_nginx | 2022/03/25 10:31:53 [notice] 1#1: nginx/1.21.6
my_wordpress_project_nginx | 2022/03/25 10:31:53 [notice] 1#1: built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1) 
my_wordpress_project_nginx | 2022/03/25 10:31:53 [notice] 1#1: OS: Linux 5.11.0-1022-aws
my_wordpress_project_nginx | 2022/03/25 10:31:53 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
my_wordpress_project_nginx | 2022/03/25 10:31:53 [notice] 1#1: start worker processes
my_wordpress_project_nginx | 2022/03/25 10:31:53 [notice] 1#1: start worker process 31
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Warning] 'proxies_priv' entry '@% root@6d081ad42455' ignored in --skip-name-resolve mode.
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] InnoDB: Buffer pool(s) load completed at 220325 10:31:59
my_wordpress_project_mariadb | 2022-03-25 10:31:59 0 [Note] mysqld: ready for connections.
my_wordpress_project_mariadb | Version: '10.7.3-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
my_wordpress_project_php | sudo -E init
my_wordpress_project_php | [25-Mar-2022 10:31:53 UTC] PHP Deprecated:  file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php on line 886
my_wordpress_project_php | [25-Mar-2022 10:31:54 UTC] PHP Deprecated:  file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php on line 886
my_wordpress_project_php | /usr/local/bin/compare_semver: line 28: ((: 10#Deprecated: value too great for base (error token is "10#Deprecated")
my_wordpress_project_php | /usr/local/bin/compare_semver: line 32: ((: 10#Deprecated: value too great for base (error token is "10#Deprecated")
my_wordpress_project_php | [25-Mar-2022 10:31:54] NOTICE: fpm is running, pid 1
my_wordpress_project_php | [25-Mar-2022 10:31:54] NOTICE: ready to handle connections
my_wordpress_project_traefik | time="2022-03-25T10:31:52Z" level=info msg="Configuration loaded from flags."

```
### SSH Config
Host wordpress
     HostName XXX.XX.XX.XXX
     User ubuntu
     ServerAliveInterval 60
     ServerAliveCountMax 120
     LocalForward 8000 wp.docker.localhost:8000
     IdentityFile spotinstance.pem

### Exception Details
This port fowarding the local machine throws a  **404 page not found**
